export default {
  contactLocation: "Melbourne, VIC",
  contactPhone: "0421 448 539",
  contactEmail: "charliemcg@protonmail.ch",
  linksAndroid: "https://bit.ly/2NulWCw",
  linksIos: "https://apple.co/2VJ7fgB",
  linksGithub: "https://bit.ly/2GP62Rk",
  linksYoutube: "https://bit.ly/2B3KzDx",
  skillsTitle: "Skills",
  skills: [
    "React",
    "JavaScript",
    "NodeJS",
    "Redux",
    "Express",
    "MongoDB",
    "Java",
    "Django",
    "Sass",
    "GraphQL",
    "Git",
    "REST APIs",
    "SQL",
    "UI/UX design",
    "Localisation",
    "Snapshot testing",
  ],
  name: "Charlie McGregor",
  role: "React Developer",
  summaryTitle: "Summary",
  summaryContent:
    "React Native/ReactJS developer with experience in all steps of the app development process. Experienced in backend development using NodeJS. Several completed apps currently available for download. Graduate of Royal Melbourne Institute of Technology majoring in Information Technology. Experienced in project development using Agile methodologies.",
  educationTitle: "Education",
  educationDegree: "Bachelor’s of IT",
  educationDegreeDate: "2015 – 2018",
  educationInstitution: "Royal Melbourne Institute of Technology (RMIT)",
  educationGpa: "GPA: 3.4",
  programmingExperienceTitle: "Programming Experience",
  programmingExperienceAppDeveloper: "Independent Application Developer",
  programmingExperienceAppDeveloperDate: "2016 - present",
  programmingExperienceApps: [
    "Tone Tracker",
    "Tip Advisor",
    "Blistful",
    "Task Killer",
    "Memory Whizz",
    "Russian Roulette",
    "Virtual Plant",
  ],
  programmingExperienceYoutube: "YouTube Content Creator",
  programmingExperienceYoutubeDate: "2018 - present",
  programmingExperienceYoutubeDescription: "Programming tutorials",
  workHistoryTitle: "Work History",
  workHistorySecurityAnalyst: "Security Analyst",
  workHistorySecurityAnalystDate: "2019 – present",
  workHistorySecurityAnalystCompany: "Infosys",
  workHistorySecurityAnalystPoints: [
    "Correcting sync issues between applications within a federated system.",
    "Migrating data between servers of different operating systems.",
    "Automating processes with Jenkins.",
    "Documenting technical processes.",
  ],
  workHistorySalesAssociate: "Sales Associate",
  workHistorySalesAssociateDate: "2012 - 2018",
  workHistorySalesAssociateCompany: "Guitar Exchange",
  workHistorySalesAssociatePoints: [
    "Used sales skills to optimise customer satisfaction while maintaining the highest profit margin on the sales team.",
    "Worked closely with customers and suppliers to determine stock which would be valuable to both customers and the shop.",
    "Performed back-end operations on the shop’s website via Magento.",
    "Regularly posted product related content and conducted marketing campaigns via Facebook.",
  ],
};
